uiuc_cms_conference_homepage:
    pattern:  /conf/
    defaults: { _controller: UiucCmsConferenceBundle:Default:index }

uiuc_cms_conference_create:
    pattern: /conf/create
    defaults: { _controller: UiucCmsConferenceBundle:Default:create }

uiuc_cms_conference_submit:
    pattern: /conf/create/submit
    defaults: { _controller: UiucCmsConferenceBundle:Default:submit }

uiuc_cms_conference_list:
    pattern: /conf/list/
    defaults: { _controller: UiucCmsConferenceBundle:Default:list }

uiuc_cms_conference_display:
    pattern: /conf/display/{id}
    defaults: { _controller: UiucCmsConferenceBundle:Default:display }




