parameters:
    uiuc_cms.payment.controller.class: UiucCms\Bundle\PaymentBundle\Controller\PaymentController

services:
    uiuc_cms.payment.controller:
        class: %uiuc_cms.payment.controller.class%
        #arguments: [@service_id, "plain_value", %parameter%]
