parameters:
    uiuc_cms.payment.controller.class: UiucCms\Bundle\PaymentBundle\Controller\PaymentController
    uiuc_cms.payment.uofi_ipay_dummy_plugin.class: UiucCms\Bundle\PaymentBundle\Plugin\UofiIpayDummyPlugin
    uiuc_cms.payment.form.uofi_ipay_type.class: UiucCms\Bundle\PaymentBundle\Form\UofiIpayType

services:
    uiuc_cms.payment.controller:
        class: %uiuc_cms.payment.controller.class%
        arguments:
            - "@router"
            - "@form.factory"
            - "@payment.plugin_controller"
            - "@doctrine.orm.entity_manager"

    uiuc_cms.payment.uofi_ipay_dummy_plugin:
        class: %uiuc_cms.payment.uofi_ipay_dummy_plugin.class%
        tags:
            - { name: payment.plugin }

    uiuc_cms.payment.form.uofi_ipay_type:
        class: %uiuc_cms.payment.form.uofi_ipay_type.class%
        tags:
            - { name: payment.method_form_type }
            - { name: form.type, alias: uofi_ipay }
