parameters:
    uiuc_cms.payment.controller.class: UiucCms\Bundle\PaymentBundle\Controller\PaymentController

services:
    uiuc_cms.payment.controller:
        class: %uiuc_cms.payment.controller.class%
        arguments:
            - "@templating"
            - "@form.factory"
            - "@router"
            - "@payment.plugin_controller"
            - "@doctrine.orm.entity_manager"
