<?php

namespace UiucCms\Bundle\ConferenceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConferenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConferenceRepository extends EntityRepository
{
}
