parameters:
#    uiuc_cms_placeholder.example.class: UiucCms\Bundle\PlaceholderBundle\Example

services:
#    uiuc_cms_placeholder.example:
#        class: %uiuc_cms_placeholder.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
