uiuc_cms_user_index:
    pattern:    /
    defaults: { _controller: UiucCmsUserBundle:Default:index }

uiuc_cms_user_profile:
    pattern:  /profile/
    defaults: { _controller: UiucCmsUserBundle:Default:profile }
