uiuc_test_user_index:
    pattern:    /
    defaults: { _controller: UiucCmsUserBundle:Default:index }

uiuc_cms_user_login:
    pattern:  /login/
    defaults: { _controller: UiucCmsUserBundle:Default:login }

