uiuc_cms_user_index:
    pattern:    /
    defaults: { _controller: UiucCmsUserBundle:Default:index }

uiuc_cms_promote_user:
    pattern:  /admin/show
    defaults: { _controller: UiucCmsAdminBundle:Default:show }
