parameters:
#    uiuc_cms_user.example.class: UiucCms\Bundle\UserBundle\Example

services:
#    uiuc_cms_user.example:
#        class: %uiuc_cms_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
