#parameters:
#    uiuc_cms_user.example.class: UiucCms\Bundle\UserBundle\Example

services:
    uiuc_cms_user.registration.form.type:
        class: UiucCms\Bundle\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: uiuc_cms_user_registration }
