UiucCms\Bundle\ConferenceBundle\Entity\Enrollment:
    type: entity
    table: null
    repositoryClass: UiucCms\Bundle\ConferenceBundle\Entity\EnrollmentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        conferenceId:
            type: integer
        attendeeId:
            type: integer
            length: 50
        enrollmentDate:
            type: datetime
        coverFeeStatus:
            type: integer
        food:
            type: string
            length: 255
        paperAbstract:
            type: string
            length: 255
    lifecycleCallbacks: {  }
