imports:
    - { resource: config_dev.yml }
    - { resource: parameters_sqlite.yml }

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_sqlite
        path: "%database_path%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
