parameters:
    database_driver: pdo_sqlite
    database_path: "%kernel.root_dir%/test.db"
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: ThisTokenIsNotSoSecretChangeIt
