uiuc_cms_conference:
    resource: "@UiucCmsConferenceBundle/Resources/config/routing.yml"
    prefix:   /

uiuc_cms_admin:
    resource: "@UiucCmsAdminBundle/Resources/config/routing.yml"
    prefix:   /

uiuc_cms_placeholder:
    resource: "@UiucCmsPlaceholderBundle/Resources/config/routing.yml"
    prefix:   /

uiuc_cms_user:
    resource: "@UiucCmsUserBundle/Resources/config/routing.yml"
    prefix:   /user

