security:
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:  ^/(user|conf)/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                #always_use_default_target_path: false
                #default_target_path: uiuc_cms_user_profile
            anonymous: ~
            logout:
                path:   fos_user_security_logout
                target: /
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/user/$, roles: ROLE_USER } #, requires_channel: https }
        - { path: ^/conf/$, roles: ROLE_USER } 
        - { path: ^/conf/create/$, roles: ROLE_USER } # This still doesn't stop people from going straight to the create conf page 
        - { path: ^/user/login/$, roles: IS_AUTHENTICATED_ANONYMOUSLY } #, requires_channel: https }
        - { path: ^/user/register/$, roles: IS_AUTHENTICATED_ANONYMOUSLY } #, requires_channel: https }
        - { path: ^/user/reset/$, roles: IS_AUTHENTICATED_ANONYMOUSLY } #, requires_channel: https }
