security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/user/login$
            anonymous: ~
            security: false

        secured_area:
            pattern:  ^/user/
            anonymous: ~
            form_login:
                check_path: uiuc_cms_user_login_check
                login_path: uiuc_cms_user_login
                always_use_default_target_path: false
                default_target_path: uiuc_cms_user_profile
            logout:
                path:   uiuc_cms_user_logout
                target: /
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/user/$, roles: ROLE_USER } #, requires_channel: https }
        - { path: ^/user/login/$, roles: IS_AUTHENTICATED_ANONYMOUSLY } #, requires_channel: https }
        - { path: ^/user/register/$, roles: IS_AUTHENTICATED_ANONYMOUSLY } #, requires_channel: https }
